"""webhook_log

Revision ID: 1d4229d9e9d6
Revises: 0001_initial_schema
Create Date: 2026-04-26 00:53:13.495508

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '1d4229d9e9d6'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_task_code', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('amr_code', sa.String(length=50), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_logs_amr_code'), 'webhook_logs', ['amr_code'], unique=False)
    op.create_index(op.f('ix_webhook_logs_method'), 'webhook_logs', ['method'], unique=False)
    op.create_index(op.f('ix_webhook_logs_robot_task_code'), 'webhook_logs', ['robot_task_code'], unique=False)
    op.alter_column('robot_types', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('robot_types', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('uq_robot_types_name'), table_name='robot_types')
    op.drop_index(op.f('ix_robot_types_name'), table_name='robot_types')
    op.create_index(op.f('ix_robot_types_name'), 'robot_types', ['name'], unique=True)
    op.alter_column('task_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('task_history', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('uq_task_history_idempotency_key'), table_name='task_history')
    op.drop_index(op.f('uq_task_history_robot_task_code'), table_name='task_history')
    op.drop_index(op.f('ix_task_history_idempotency_key'), table_name='task_history')
    op.create_index(op.f('ix_task_history_idempotency_key'), 'task_history', ['idempotency_key'], unique=True)
    op.drop_index(op.f('ix_task_history_robot_task_code'), table_name='task_history')
    op.create_index(op.f('ix_task_history_robot_task_code'), 'task_history', ['robot_task_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_history_robot_task_code'), table_name='task_history')
    op.create_index(op.f('ix_task_history_robot_task_code'), 'task_history', ['robot_task_code'], unique=False)
    op.drop_index(op.f('ix_task_history_idempotency_key'), table_name='task_history')
    op.create_index(op.f('ix_task_history_idempotency_key'), 'task_history', ['idempotency_key'], unique=False)
    op.create_index(op.f('uq_task_history_robot_task_code'), 'task_history', ['robot_task_code'], unique=True)
    op.create_index(op.f('uq_task_history_idempotency_key'), 'task_history', ['idempotency_key'], unique=True)
    op.alter_column('task_history', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('task_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_robot_types_name'), table_name='robot_types')
    op.create_index(op.f('ix_robot_types_name'), 'robot_types', ['name'], unique=False)
    op.create_index(op.f('uq_robot_types_name'), 'robot_types', ['name'], unique=True)
    op.alter_column('robot_types', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('robot_types', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_webhook_logs_robot_task_code'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_method'), table_name='webhook_logs')
    op.drop_index(op.f('ix_webhook_logs_amr_code'), table_name='webhook_logs')
    op.drop_table('webhook_logs')
    # ### end Alembic commands ###
